#[derive(Debug, Clone, Copy, PartialEq, Eq)]
#[repr(i32)]
pub enum TokenKind {
    Eof = 0,
    Identifier = 1,
    Integer = 2,
    Float = 3,
    String = 4,
    Duration = 5,
    Let = 6,
    Fn = 7,
    Return = 8,
    If = 9,
    Else = 10,
    While = 11,
    For = 12,
    In = 13,
    Match = 14,
    Parallel = 15,
    True = 16,
    False = 17,
    Null = 18,
    Get = 19,
    Post = 20,
    Put = 21,
    Patch = 22,
    Delete = 23,
    Head = 24,
    Plus = 25,
    Minus = 26,
    Star = 27,
    Slash = 28,
    Percent = 29,
    Equal = 30,
    EqualEqual = 31,
    Bang = 32,
    BangEqual = 33,
    Less = 34,
    LessEqual = 35,
    Greater = 36,
    GreaterEqual = 37,
    AndAnd = 38,
    OrOr = 39,
    LeftParen = 40,
    RightParen = 41,
    LeftBrace = 42,
    RightBrace = 43,
    LeftBracket = 44,
    RightBracket = 45,
    Comma = 46,
    Colon = 47,
    Semicolon = 48,
    Dot = 49,
    FatArrow = 50,
    Tcp = 51,
    Udp = 52,
    Send = 53,
    Receive = 54,
    To = 55,
    Using = 56,
}
impl TokenKind {
    pub(crate) fn from_raw(raw: i32) -> Option<Self> {
        match raw {
            0 => Some(Self::Eof),
            1 => Some(Self::Identifier),
            2 => Some(Self::Integer),
            3 => Some(Self::Float),
            4 => Some(Self::String),
            5 => Some(Self::Duration),
            6 => Some(Self::Let),
            7 => Some(Self::Fn),
            8 => Some(Self::Return),
            9 => Some(Self::If),
            10 => Some(Self::Else),
            11 => Some(Self::While),
            12 => Some(Self::For),
            13 => Some(Self::In),
            14 => Some(Self::Match),
            15 => Some(Self::Parallel),
            16 => Some(Self::True),
            17 => Some(Self::False),
            18 => Some(Self::Null),
            19 => Some(Self::Get),
            20 => Some(Self::Post),
            21 => Some(Self::Put),
            22 => Some(Self::Patch),
            23 => Some(Self::Delete),
            24 => Some(Self::Head),
            25 => Some(Self::Plus),
            26 => Some(Self::Minus),
            27 => Some(Self::Star),
            28 => Some(Self::Slash),
            29 => Some(Self::Percent),
            30 => Some(Self::Equal),
            31 => Some(Self::EqualEqual),
            32 => Some(Self::Bang),
            33 => Some(Self::BangEqual),
            34 => Some(Self::Less),
            35 => Some(Self::LessEqual),
            36 => Some(Self::Greater),
            37 => Some(Self::GreaterEqual),
            38 => Some(Self::AndAnd),
            39 => Some(Self::OrOr),
            40 => Some(Self::LeftParen),
            41 => Some(Self::RightParen),
            42 => Some(Self::LeftBrace),
            43 => Some(Self::RightBrace),
            44 => Some(Self::LeftBracket),
            45 => Some(Self::RightBracket),
            46 => Some(Self::Comma),
            47 => Some(Self::Colon),
            48 => Some(Self::Semicolon),
            49 => Some(Self::Dot),
            50 => Some(Self::FatArrow),
            51 => Some(Self::Tcp),
            52 => Some(Self::Udp),
            53 => Some(Self::Send),
            54 => Some(Self::Receive),
            55 => Some(Self::To),
            56 => Some(Self::Using),
            _ => None,
        }
    }
}
#[derive(Debug, Clone, PartialEq, Eq)]
pub struct Token {
    pub kind: TokenKind,
    pub lexeme: String,
    pub line: usize,
    /// One-based UTF-8 byte column.
    pub column: usize,
}

impl Token {
    pub fn span(&self) -> crate::source::Span {
        let start = crate::source::Position {
            line: self.line,
            column: self.column,
        };
        crate::source::Span::from_text(
            start,
            if self.kind == TokenKind::Eof {
                ""
            } else {
                &self.lexeme
            },
        )
    }
}

impl TokenKind {
    pub fn name(self) -> &'static str {
        match self {
            Self::Eof => "EOF",
            Self::Identifier => "IDENTIFIER",
            Self::Integer => "INTEGER",
            Self::Float => "FLOAT",
            Self::String => "STRING",
            Self::Duration => "DURATION",
            Self::Let => "LET",
            Self::Fn => "FN",
            Self::Return => "RETURN",
            Self::If => "IF",
            Self::Else => "ELSE",
            Self::While => "WHILE",
            Self::For => "FOR",
            Self::In => "IN",
            Self::Match => "MATCH",
            Self::Parallel => "PARALLEL",
            Self::True => "TRUE",
            Self::False => "FALSE",
            Self::Null => "NULL",
            Self::Get => "GET",
            Self::Post => "POST",
            Self::Put => "PUT",
            Self::Patch => "PATCH",
            Self::Delete => "DELETE",
            Self::Head => "HEAD",
            Self::Plus => "PLUS",
            Self::Minus => "MINUS",
            Self::Star => "STAR",
            Self::Slash => "SLASH",
            Self::Percent => "PERCENT",
            Self::Equal => "EQUAL",
            Self::EqualEqual => "EQUAL_EQUAL",
            Self::Bang => "BANG",
            Self::BangEqual => "BANG_EQUAL",
            Self::Less => "LESS",
            Self::LessEqual => "LESS_EQUAL",
            Self::Greater => "GREATER",
            Self::GreaterEqual => "GREATER_EQUAL",
            Self::AndAnd => "AND_AND",
            Self::OrOr => "OR_OR",
            Self::LeftParen => "LEFT_PAREN",
            Self::RightParen => "RIGHT_PAREN",
            Self::LeftBrace => "LEFT_BRACE",
            Self::RightBrace => "RIGHT_BRACE",
            Self::LeftBracket => "LEFT_BRACKET",
            Self::RightBracket => "RIGHT_BRACKET",
            Self::Comma => "COMMA",
            Self::Colon => "COLON",
            Self::Semicolon => "SEMICOLON",
            Self::Dot => "DOT",
            Self::FatArrow => "FAT_ARROW",
            Self::Tcp => "TCP",
            Self::Udp => "UDP",
            Self::Send => "SEND",
            Self::Receive => "RECEIVE",
            Self::To => "TO",
            Self::Using => "USING",
        }
    }
}
