#[derive(Debug, Clone, Copy, PartialEq, Eq)]
#[repr(i32)]
pub enum TokenKind {
    Eof = 0,
    Identifier = 1,
    Integer = 2,
    Float = 3,
    String = 4,
    Duration = 5,
    Let = 6,
    Fn = 7,
    Return = 8,
    If = 9,
    Else = 10,
    While = 11,
    For = 12,
    In = 13,
    Match = 14,
    Parallel = 15,
    True = 16,
    False = 17,
    Null = 18,
    Get = 19,
    Post = 20,
    Put = 21,
    Patch = 22,
    Delete = 23,
    Head = 24,
    Plus = 25,
    Minus = 26,
    Star = 27,
    Slash = 28,
    Percent = 29,
    Equal = 30,
    EqualEqual = 31,
    Bang = 32,
    BangEqual = 33,
    Less = 34,
    LessEqual = 35,
    Greater = 36,
    GreaterEqual = 37,
    AndAnd = 38,
    OrOr = 39,
    LeftParen = 40,
    RightParen = 41,
    LeftBrace = 42,
    RightBrace = 43,
    LeftBracket = 44,
    RightBracket = 45,
    Comma = 46,
    Colon = 47,
    Semicolon = 48,
    Dot = 49,
    FatArrow = 50,
}
impl TokenKind {
    pub(crate) fn from_raw(raw: i32) -> Option<Self> {
        match raw {
            0 => Some(Self::Eof),
            1 => Some(Self::Identifier),
            2 => Some(Self::Integer),
            3 => Some(Self::Float),
            4 => Some(Self::String),
            5 => Some(Self::Duration),
            6 => Some(Self::Let),
            7 => Some(Self::Fn),
            8 => Some(Self::Return),
            9 => Some(Self::If),
            10 => Some(Self::Else),
            11 => Some(Self::While),
            12 => Some(Self::For),
            13 => Some(Self::In),
            14 => Some(Self::Match),
            15 => Some(Self::Parallel),
            16 => Some(Self::True),
            17 => Some(Self::False),
            18 => Some(Self::Null),
            19 => Some(Self::Get),
            20 => Some(Self::Post),
            21 => Some(Self::Put),
            22 => Some(Self::Patch),
            23 => Some(Self::Delete),
            24 => Some(Self::Head),
            25 => Some(Self::Plus),
            26 => Some(Self::Minus),
            27 => Some(Self::Star),
            28 => Some(Self::Slash),
            29 => Some(Self::Percent),
            30 => Some(Self::Equal),
            31 => Some(Self::EqualEqual),
            32 => Some(Self::Bang),
            33 => Some(Self::BangEqual),
            34 => Some(Self::Less),
            35 => Some(Self::LessEqual),
            36 => Some(Self::Greater),
            37 => Some(Self::GreaterEqual),
            38 => Some(Self::AndAnd),
            39 => Some(Self::OrOr),
            40 => Some(Self::LeftParen),
            41 => Some(Self::RightParen),
            42 => Some(Self::LeftBrace),
            43 => Some(Self::RightBrace),
            44 => Some(Self::LeftBracket),
            45 => Some(Self::RightBracket),
            46 => Some(Self::Comma),
            47 => Some(Self::Colon),
            48 => Some(Self::Semicolon),
            49 => Some(Self::Dot),
            50 => Some(Self::FatArrow),
            _ => None,
        }
    }
}
#[derive(Debug, Clone, PartialEq, Eq)]
pub struct Token {
    pub kind: TokenKind,
    pub lexeme: String,
    pub line: usize,
    /// One-based UTF-8 byte column.
    pub column: usize,
}
